SELECT *
FROM "Covid"
WHERE CONTINENT IS NOT NULL

-- Total Cases vs Total Deaths

SELECT LOCATION, date, TOTAL_CASES,
	TOTAL_DEATHS,
	(CAST (TOTAL_DEATHS AS float) / TOTAL_CASES) * 100 AS DEATHPERCENTAGE
FROM "Covid"
WHERE LOCATION = 'India'
				AND CONTINENT IS NOT NULL
ORDER BY 2


-- Total Cases vs Population

SELECT LOCATION, date, POPULATION,
	TOTAL_CASES,
	(CAST (TOTAL_CASES AS float) / POPULATION) * 100 AS PERCENTPOPULATIONINFECTED
FROM "Covid"
ORDER BY 1,2


-- Countries with Highest Infection Rate compared to Population

SELECT LOCATION,
	POPULATION,
	MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT,
	MAX((CAST(TOTAL_CASES AS float) / POPULATION)) * 100 AS PERCENTPOPULATIONINFECTED
FROM "Covid"
WHERE TOTAL_CASES IS NOT NULL
GROUP BY LOCATION,
	POPULATION
ORDER BY PERCENTPOPULATIONINFECTED DESC


-- Countries with Highest Death Count per Population

SELECT LOCATION,
	MAX(CAST(TOTAL_DEATHS AS int)) AS TOTALDEATHCOUNT
FROM "Covid"
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTALDEATHCOUNT DESC


-- Showing contintents with the highest death count per population

SELECT CONTINENT,
	MAX(CAST(TOTAL_DEATHS AS int)) AS TOTALDEATHCOUNT
FROM "Covid"
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TOTALDEATHCOUNT DESC



-- GLOBAL NUMBERS

SELECT SUM(NEW_CASES) AS TOTAL_CASES,
	SUM(CAST(NEW_DEATHS AS int)) AS TOTAL_DEATHS,
	SUM(CAST(NEW_DEATHS AS int)) / SUM(NEW_CASES) * 100 AS DEATHPERCENTAGE
FROM "Covid"
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2



-- Total Population vs Vaccinations
-- Shows Percentage of Population that has recieved at least one Covid Vaccine

SELECT DEA.CONTINENT,
	DEA.LOCATION,
	DEA.DATE,
	DEA.POPULATION,
	VAC.NEW_VACCINATIONS,
	SUM(VAC.NEW_VACCINATIONS) OVER (PARTITION BY DEA.LOCATION
										 ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM "Covid" DEA
JOIN "Vaccination" VAC ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3


WITH VACC (CONTINENT,LOCATION,date,POPULATIO,NEW_VACCINATIONS,PEOPLE_VACCINATED_UPTO_DATE) AS
				(SELECT DEA.CONTINENT,
						DEA.LOCATION,
						DEA.DATE,
						DEA.POPULATION,
						VAC.NEW_VACCINATIONS,
						SUM(VAC.NEW_VACCINATIONS) OVER (PARTITION BY DEA.LOCATION
														     ORDER BY DEA.LOCATION,DEA.DATE) AS PEOPLE_VACCINATED_UPTO_DATE
					FROM "Covid" DEA
					JOIN "Vaccination" VAC ON DEA.LOCATION = VAC.LOCATION
					AND DEA.DATE = VAC.DATE
					WHERE DEA.CONTINENT IS NOT NULL
					ORDER BY 2,3)
SELECT *,
	(PEOPLE_VACCINATED_UPTO_DATE / POPULATION) * 100 AS PERCENTAGE
FROM VACC


CREATE TABLE PUBLIC."PercentPopulationVaccinated" (CONTINENT varchar, LOCATION varchar, Date date, POPULATION numeric, NEW_VACCINATIONS numeric, PEOPLE_VACCINATED_UPTO_DATE numeric) WITH (OIDS = FALSE) TABLESPACE PG_DEFAULT;


ALTER TABLE PUBLIC."Covid" OWNER TO POSTGRES;
	
INSERT INTO "PercentPopulationVaccinated"
SELECT DEA.CONTINENT,
	DEA.LOCATION,
	DEA.DATE,
	DEA.POPULATION,
	VAC.NEW_VACCINATIONS,
	SUM(VAC.NEW_VACCINATIONS) OVER (PARTITION BY DEA.LOCATION
								         ORDER BY DEA.LOCATION,DEA.DATE) AS PEOPLE_VACCINATED_UPTO_DATE
FROM "Covid" DEA
JOIN "Vaccination" VAC ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
	

CREATE VIEW PERCENTPOPULATIONVACCINATED AS
SELECT DEA.CONTINENT,
	DEA.LOCATION,
	DEA.DATE,
	DEA.POPULATION,
	VAC.NEW_VACCINATIONS,
	SUM(VAC.NEW_VACCINATIONS) OVER (PARTITION BY DEA.LOCATION
									    ORDER BY DEA.LOCATION,DEA.DATE) AS PEOPLE_VACCINATED_UPTO_DATE
FROM "Covid" DEA
JOIN "Vaccination" VAC ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL